### ISSUE TITLE
How can I get BGProdKlarnaView height?

### ISSUE THREAD

**Issue by hanorz** [klarna/klarna-mobile-sdk#110]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I set translatesAutoresizingMaskIntoConstraints = NO, I can not get BGProdKlarnaView height after data loading.

I put  BGProdKlarnaView  into tableview cell ,so I need to know to height of it.

**Comment by polar133** [comment]
Hi @hanorz, thanks for reaching out. I think you are asking about the event listener in the Payment view, in the docs you can find more information: https://docs.klarna.com/in-app/inapp-ios-overview/klarna-payments-native/#handling-height-changes

**Comment by hanorz** [comment]
> Hi @hanorz, thanks for reaching out. I think you are asking about the event listener in the Payment view, in the docs you can find more information: https://docs.klarna.com/in-app/inapp-ios-overview/klarna-payments-native/#handling-height-changes

Thanks. I think this is it！

**Comment by hanorz** [comment]
I think there is KlarnaOSMViewEventListener can return the height after loading KlarnaOSMView
