### ISSUE TITLE
Can not use KlarnaOSMViewEventListener either OC or Swift

### ISSUE THREAD

**Issue by hanorz** [klarna/klarna-mobile-sdk#111]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device and version:**
 - OS version: [e.g. iOS8.1]
 - Klarna In-App SDK version [e.g. 1.2.3]

**Merchant Name**
Please state the merchant's name and the application's name that is facing the issue using the SDK.

**Impact Level**
What is the impact level of this bug on the merchant and its customers? Is it happening in production? Is it a blocking issue for development?  etc. 

**Additional context**

sdk version:2.0.43

My project was base on OC,  and I want to show KlarnaOSMView in my view. I want to get dynamic height by KlarnaOSMViewEventListener, but in oc, there is no delegate in KlarnaOSMView.

![WeChat2fc66743c414dc6929310c514695bc47](https://user-images.githubusercontent.com/9412189/132353779-feaa6c41-7d37-4d43-9f0d-53702f6955a2.png)

![WeChatbd94ef4bfffc4a995d2e4b64aca4d403](https://user-images.githubusercontent.com/9412189/132354009-262c14b2-8c0a-4366-8133-aa511ccb33e4.png)

So I try swift, but shows error by KlarnaOSMViewEventListener.

![WeChat03872c7516cddc8aecd724f7e77a398c](https://user-images.githubusercontent.com/9412189/132353530-d1eabdfc-1377-4bec-8153-706953890e73.png)
 urgent.

What can I do? it's

**Comment by hanorz** [comment]
I think there is no @objc to the delegate, so the oc can't recognize it?

**Comment by polar133** [comment]
Hi @hanorz, thanks for informing us about this issue. Yes, the delegate property was not exposed as @ objc. We will fix it asap and release a new version during the day. We will let you know when it's ready.

**Comment by hanorz** [comment]
> Hi @hanorz, thanks for informing us about this issue. Yes, the delegate property was not exposed as @ objc. We will fix it asap and release a new version during the day. We will let you know when it's ready.

Thank you

**Comment by polar133** [comment]
Hi @hanorz we release version 2.0.44, please give a try and let us know how it did go.

**Comment by hanorz** [comment]
> Hi @hanorz we release version 2.0.44, please give a try and let us know how it did go.

Trying.

**Comment by hanorz** [comment]
> Hi @hanorz we release version 2.0.44, please give a try and let us know how it did go.

It fixed. Thank you.

**Comment by polar133** [comment]
> > Hi @hanorz we release version 2.0.44, please give a try and let us know how it did go.
> 
> It fixed. Thank you.

Great. I will close the ticket and in case there are any other issue please let us know.
