### ISSUE TITLE
Can not show Staging View after using 2.0.44 version SDK

### ISSUE THREAD

**Issue by hanorz** [klarna/klarna-mobile-sdk#113]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device and version:**
 - OS version: [e.g. iOS8.1]
 - Klarna In-App SDK version 2.0.44

**Merchant Name**
Please state the merchant's name and the application's name that is facing the issue using the SDK.

**Impact Level**
What is the impact level of this bug on the merchant and its customers? Is it happening in production? Is it a blocking issue for development?  etc. 

**Additional context**

After using 2.0.44 version SDK, the tap action of the KlarnaOSMView was disable. Which
 means it can not show the Staging view.
And I tried many times figured out the KlarnaOSMView only respond  the small area in the picture.

![WeChatd88f540cd9c6c1481e3f45eaffa7dd18](https://user-images.githubusercontent.com/9412189/132789909-a60df6b6-57ef-4d5c-9eca-657fe5ce3cc5.png)

**Comment by polar133** [comment]
Hi, @hanorz can you please share the device and OS that you are using for testing? On our end, the label with the underline works correctly to detect the tap gesture that opens the fullscreen view.

**Comment by hanorz** [comment]
> Hi, @hanorz can you please share the device and OS that you are using for testing? On our end, the label with the underline works correctly to detect the tap gesture that opens the fullscreen view.

I am using iPhone 12 simulator(14.5) and iPhone 8 real device(14.4).

**Comment by hanorz** [comment]
> Hi, @hanorz can you please share the device and OS that you are using for testing? On our end, the label with the underline works correctly to detect the tap gesture that opens the fullscreen view.

The screenshot picture was build in  iPhone 12 simulator(14.5), there is nothing else on the project, only 2.0.44 SDK

**Comment by polar133** [comment]
> > Hi, @hanorz can you please share the device and OS that you are using for testing? On our end, the label with the underline works correctly to detect the tap gesture that opens the fullscreen view.
> 
> The screenshot picture was build in iPhone 12 simulator(14.5), there is nothing else on the project, only 2.0.44 SDK

Thanks for the info. We will try to replicate the same issue. Meanwhile, can you try the OSM with the environment = .demo, it should render a static osm view, please, check if that view has the same issue. tap in any part of the underline and should open a fullscreen. Let us know if that one works please.

**Comment by hanorz** [comment]
> > > Hi, @hanorz can you please share the device and OS that you are using for testing? On our end, the label with the underline works correctly to detect the tap gesture that opens the fullscreen view.
> > 
> > 
> > The screenshot picture was build in iPhone 12 simulator(14.5), there is nothing else on the project, only 2.0.44 SDK
> 
> Thanks for the info. We will try to replicate the same issue. Meanwhile, can you try the OSM with the environment = .demo, it should render a static osm view, please, check if that view has the same issue. tap in any part of the underline and should open a fullscreen. Let us know if that one works please.

Just tried. Same issue, nothing react by tap.

**Comment by hanorz** [comment]
Only react by this small area.
![企业微信截图_6aaa55f2-07ab-4a2e-9712-e2b1bd29a8d4](https://user-images.githubusercontent.com/9412189/132844590-5d98ce4a-3693-4d4d-bf4e-4032dd3c8422.png)

**Comment by polar133** [comment]
@hanorz thanks. Could you share how the[ Debug View Hierarchy](https://developer.apple.com/library/archive/documentation/ToolsLanguages/Conceptual/Xcode_Overview/ExaminingtheViewHierarchy.html) looks for that element please ? also, which version of xcode ?

**Comment by hanorz** [comment]
> @hanorz thanks. Could you share how the[ Debug View Hierarchy](https://developer.apple.com/library/archive/documentation/ToolsLanguages/Conceptual/Xcode_Overview/ExaminingtheViewHierarchy.html) looks for that element please ? also, which version of xcode ?

![WeChatcab847a3e3d9eb1b2d3e0228c05dae23](https://user-images.githubusercontent.com/9412189/132852796-18dff508-fcd0-411d-b676-b8fb32d5fecc.png)

![WeChat5b2c06dda2ebcd5ceb7ffb2eaaa94f98](https://user-images.githubusercontent.com/9412189/132852899-0ca1482e-2315-41b8-864e-c76754aad0a6.png)

![WeChat5895b24ec36c2e6a47b1e2de3fbccb04](https://user-images.githubusercontent.com/9412189/132853045-51c05bed-4ce8-4b2f-9dee-3b369e223425.png)

Version 12.5.1 for Xcode

**Comment by hanorz** [comment]
> @hanorz thanks. Could you share how the[ Debug View Hierarchy](https://developer.apple.com/library/archive/documentation/ToolsLanguages/Conceptual/Xcode_Overview/ExaminingtheViewHierarchy.html) looks for that element please ? also, which version of xcode ?

I can send you the demo project if you need.

**Comment by polar133** [comment]
@hanorz thanks for the info. It looks like it's a height constraint on the OSM view in the implementation. Make sure to extend _KlarnaOSMViewEventListener_ and use the height sent in _klarnaOSMViewResized_, and update the height constraint for the OSM view with the new height sent. 

![132853045-51c05bed-4ce8-4b2f-9dee-3b369e223425](https://user-images.githubusercontent.com/1957429/132855394-af41b686-6e08-4dbc-9be5-ca5ab9de579b.png)

**Comment by hanorz** [comment]
> @hanorz thanks for the info. It looks like it's a height constraint on the OSM view in the implementation. Make sure to extend _KlarnaOSMViewEventListener_ and use the height sent in _klarnaOSMViewResized_, and update the height constraint for the OSM view with the new height sent.
> 
> ![132853045-51c05bed-4ce8-4b2f-9dee-3b369e223425](https://user-images.githubusercontent.com/1957429/132855394-af41b686-6e08-4dbc-9be5-ca5ab9de579b.png)

**Comment by hanorz** [comment]
It works.Thanks you.
