### ISSUE TITLE
Swift Compiler Warning: arm64-apple-ios.swiftsourceinfo is either malformed or generated by a different Swift version

### ISSUE THREAD

**Issue by AmyNgithub** [klarna/klarna-mobile-sdk#115]
**Describe the bug**
After updating to Xcode 13.0 the line:
`import KlarnaMobileSDK`
Triggers Swift Compiler Warning with the following message:
" ... Pods/KlarnaMobileSDK/ios/full/xcode-12.3-fat/KlarnaMobileSDK.framework/Modules/KlarnaMobileSDK.swiftmodule/Project/arm64-apple-ios.swiftsourceinfo' is either malformed or generated by a different Swift version. Note that it uses an unstable format and may leak internal project details, it should not be distributed alongside modules"

**To Reproduce**
1. Install version 2.0.44 of KlarnaMobileSDK
2. Update Xcode to version 13.0
3. Open project in Xcode
4. Run the app
5. The warning then occurs in Issue navigator under Buildtime tab.

**Expected behavior**
Running the app should not trigger a Swift Complier Warning.

**Screenshots**
N/A

**Device and version:**
 - Device: iPhone 12 Pro
 - OS version: 14.4.1
 - Klarna In-App SDK version: 2.0.44
 - Xcode version: 13.0

**Merchant Name**
I'd rather not state this here unless absolutely necessary.

**Impact Level**
The full impact has not yet been determined but so far the app still compiles and runs OK in Xcode

**Additional context**
Noted that no Swift Compiler Warning was triggered when using Xcode version 12.4. Combined with the fact "xcode-12.3" is mentioned in the path in the warning message, I'm guessing that "generated by a different Swift version" is probably the cause. 

My app still compiles and runs OK on an iPhone 12 Pro so probably not a critical issue. But "unstable format and may leak internal project details, it should not be distributed alongside modules" does not sound good for a release on App Store.

**Comment by gbanfalvikl** [comment]
Thanks for the heads up, we created an internal bug ticket and will be looking into it ASAP!

**Comment by AmyNgithub** [comment]
Thanks! Please keep me posted on the progress :)

**Comment by ksmandersen** [comment]
@jorgepalac1o We're also on latest Cocoapods 1.11.2 and KlarnaSDK 2.0.44. Downgrading cocoa pods does not work for us either. The warning persists.

**Comment by peboozt** [comment]
We have the same problem, which is blocking us from upgrading to XCode 13.

we are using klarna-mobile-sdk-basic-spm 2.0.44

**Comment by AmyNgithub** [comment]
Any update on this? :)

**Comment by ksmandersen** [comment]
@AmyNgithub Version 2.1.0 resolved this issue for us.

**Comment by AmyNgithub** [comment]
@ksmandersen Thanks! 
Upgraded to 2.1.1 and now the issue is gone for me too. 
Closing this issue :)
