### ISSUE TITLE
Seems proguard  file not contain "-dontusemixedcaseclassnames" command

### ISSUE THREAD

**Issue by 54lazycat** [klarna/klarna-mobile-sdk#116]
**Describe the bug**
when I import  klarna SDK. Sometime build failed.

log info:

Caused by: com.android.tools.r8.errors.b: Class content provided for type descriptor com.getbouncer.cardscan.base.r actually defines class com.getbouncer.cardscan.base.R

it looks like Klarna dependent on getbouncer library. And the proguard file don't contain "-dontusemixedcaseclassnames" command. So at some filesystem while get failed.

**Comment by NMGuner** [comment]
We updated our proguard rules multiple times and we haven't face this issue for a while, thus I will be closing this but feel free to open it again if it still happens in the latest Android version.
