### ISSUE TITLE
Deprecated API Usage - UIWebView

### ISSUE THREAD

**Issue by stickmanlechu** [klarna/klarna-mobile-sdk#12]
Hello! After uploading the app to App Store Connect I got a message from the team stating:
`We identified one or more issues with a recent delivery for your app, (...) ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs `. After running a grep searching for UIWebView, KlarnaMobileSDK was the only result to appear.

**To Reproduce**
1. Add KlarnaMobileSDK to your app.
2. Upload the app to App Store Connect.

**Additional context**
As I've seen in the issues for the Checkout SDK (https://github.com/klarna/kco-mobile-sdk/issues/34) you probably are aware of the problem, however there is already an upload deadline for apps that use UIWebView  (https://developer.apple.com/news/?id=12232019b):

`The App Store will no longer accept new apps using UIWebView as of April 2020 and app updates using UIWebView as of December 2020.
`

**Comment by omarbh** [comment]
Hi Mateusz, thanks for sharing this with us. The next release will not contain the UIWebview support anymore.

**Comment by omarbh** [comment]
Hi @stickmanlechu , we have published the new release which contains the removal of UiWbeview and other improvements, check it out here : https://github.com/klarna/klarna-mobile-sdk/blob/master/CHANGELOG.md
