### ISSUE TITLE
Hybrid Integration on Android  

### ISSUE THREAD

**Issue by leon2017** [klarna/klarna-mobile-sdk#13]
**Describe the bug**
Hello,I referred to the extensive documentation to integrate your SDK. When I clicked the relevant agreement on the payment page, I flipped two layers of the dialog to let me choose the default browser without setting the default browser, as in this video

**To Reproduce**
1. Go to 'webview pay'
2. Click on 'User-related agreement'

**Screenshots**
https://youtu.be/NWql0KKZYSQ

**Device and version:**
 - Device: [e.g. Nokia X6 、Samsung S9]
 - OS: [e.g. android 9.0]
 - SDK Version [e.g. 28]

**Comment by omarbh** [comment]
Hi @leon2017 thanks for reporting this, we will look into it and get back to asap !

**Comment by mahmoudjafarinejad** [comment]
Hi @leon2017. Could I ask which Klarna In-App SDK version you are using? If you're not using the latest version, please update it to the latest one and check if it's still behaving the same way.

**Comment by leon2017** [comment]
> Hi @leon2017. Could I ask which Klarna In-App SDK version you are using? If you're not using the latest version, please update it to the latest one and check if it's still behaving the same way.

**Comment by leon2017** [comment]
> Hi @leon2017. Could I ask which Klarna In-App SDK version you are using? If you're not using the latest version, please update it to the latest one and check if it's still behaving the same way.

Hi @mahmoudjafarinejad ,
implementation 'com.klarna.mobile:sdk:2.0.0'
