### ISSUE TITLE
Payment fails if app has a non-alphanumeric name

### ISSUE THREAD

**Issue by piercifani** [klarna/klarna-mobile-sdk#150]
**Describe the bug**
The SDK infers the merchant name using the app's name. However, if the app's name contains a non-alphanumeric name (such as special characters or emojis), starting the SDK fails.
 
**To Reproduce**
1. Name your app something like "Klarnaβ"
2. Start the SDK to attempt a payment
3. Receive the error

**Expected behavior**
The SDK should either: 
- Escape all non-supported characters on its end, as it's querying the app's name using NSBundle APIs
- Add an API to pass the merchant name programmatically and not infer it using NSBundle APIs

**Screenshots**
<img width="2131" alt="Screenshot 2022-07-28 at 13 04 12" src="https://user-images.githubusercontent.com/869981/182786897-21f0b60e-59f6-4cb6-92d1-204deebc3caf.png">

**Device and version:**
 - Device: Any iOS Device
 - OS version: Any iOS Version
 - Klarna In-App SDK version 2.2.0

**Merchant Name**
NaturitasES

**Impact Level**
Can't proceed with integration 

**Additional context**
None

**Comment by polar133** [comment]
Hi @piercifani. Thanks for the comment. The 403 response has been made intentionally from our end, but it should only affect event logging. Hence the SDK should work as expected. This should impact all requests to the same endpoint regardless of the content of the request.

**Comment by piercifani** [comment]
Hello @polar133 , thanks for the quick response.

However, this 403 is not the only error we see in our end, but also the SDK fails to [load the payment](https://user-images.githubusercontent.com/869981/182792374-0d4b7705-02c1-46d5-82db-991a7baae065.png) as you can see in this screenshot.

Changing our app's name to alphanumeric characters, fixes it. So this definitely has something to do with it.

**Comment by polar133** [comment]
oh got it. Thanks for the clarification. I will share it internally and be back when I have updates to share.

**Comment by piercifani** [comment]
Hey guys, summer has passed and still no news here. Any updates?

**Comment by NMGuner** [comment]
Hi there, sorry for the late response, this has been addressed on a previous release. Unfortunately, we forgot to mention it here, [this](https://github.com/klarna/klarna-mobile-sdk/blob/master/CHANGELOG.md#232---2022-10-31) is the changelog item of the release for future reference.

**Comment by Smail-cai** [comment]
This is still the case with Android
