### ISSUE TITLE
iOS app rejected due to ITMS-90683: Missing Purpose String for NSCameraUsageDescription despite using KlarnaMobileSDK/basic

### ISSUE THREAD

**Issue by AmyNgithub** [klarna/klarna-mobile-sdk#151]
**Describe the bug**
The iOS app I'm working on gets rejected due to ITMS-90683: Missing Purpose String for NSCameraUsageDescription despite using KlarnaMobileSDK/basic. I thought the basic version did not include the card scanning feature and therefore did not require the NSCameraUsageDescription?

**To Reproduce**
1. Add `pod 'KlarnaMobileSDK/basic','2.1.6'` to podfile
2. Run `pod install`
3. Archive and upload app to AppStoreConnect
4. After a while I receive an email from AppStoreConnect:
"Dear Developer,
We identified one or more issues with a recent delivery for your app. Please correct the following issues, then upload again.

ITMS-90683: Missing Purpose String in Info.plist - Your app‘s code references one or more APIs that access sensitive user data. The app‘s Info.plist file should contain a NSCameraUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources

Best regards,
The App Store Team"

**Expected behavior**
The app should upload to AppStoreConnect without having to specify the NSCameraUsageDescription in the info.plist

**Screenshots**
N/A

**Device and version:**
 - Device: N/A
 - OS version: N/A
 - Klarna In-App SDK version: 2.1.6 (basic)

**Merchant Name**

**Impact Level**
Prevents release which is required to update the KlarnaMobileSDK in the app.

**Additional context**
N/A

**Comment by polar133** [comment]
Hi @AmyNgithub Thanks for the info, we will check it out.

**Comment by polar133** [comment]
Hi @AmyNgithub, we have released a new version (v 2.2.2) that should remove the references. Sorry for any inconvenience. It was an issue in our pipeline that didn't exclude the files for the card scan. Please, give it a try and let us know how it goes.

**Comment by AmyNgithub** [comment]
Thanks for the fast response and fix time @polar133!
Version 2.2.2 resolved the issue.
