### ISSUE TITLE
KlarnaHybridEventListener functions not triggered

### ISSUE THREAD

**Issue by AmyNgithub** [klarna/klarna-mobile-sdk#18]
**Describe the bug**
The problem:
- KlarnaHybridEventListener functions are no longer triggered.
- I rely on those functions to hide my tab-bar so that I can display the Klarna popup registration form properly.

What I did before the problem occurred:
1. Updated to version 2.0.9 from 2.0.8 to resolve one of your previous issues: https://github.com/klarna/klarna-mobile-sdk/issues/12
2. Updated my implementation to use KlarnaHybridEventListener instead of the (according to xCode) deprecated KlarnaHybridSDKEventListener with the help of the integration guides:
- https://developers.klarna.com/documentation/in-app/ios/getting-started/
- https://developers.klarna.com/documentation/in-app/ios/steps-hybrid/

**To Reproduce**
1. Add: pod “KlarnaMobileSDK”, “>=2.0.9” to the Podfile
2. run pod install
3. Add something similar to the following code:

```
import KlarnaMobileSDK
class MyClass : KlarnaHybridEventListener {

    var klarnaSDK:KlarnaHybridSDK! 
    var myWebView : WKWebView!

    
    override func viewDidLoad() {
        super.viewDidLoad()
	//Set up webview
	myWebView = WKWebView(frame: self.view.frame, configuration: config)
        KlarnaMobileSDKCommon.setLoggingLevel(.verbose)
        klarnaSDK = KlarnaHybridSDK(returnUrl: URL(string: “myapp://“)!, eventListener: self )
        klarnaSDK.addWebView(self.myWebView)

	...
   }

    func webView(_ webView: WKWebView, didStartProvisionalNavigation navigation: WKNavigation!) {
        klarnaSDK?.newPageLoad(in: logicWebView)
    }
    
    func webView(_ webView: WKWebView, decidePolicyFor navigationAction: WKNavigationAction, decisionHandler: @escaping (WKNavigationActionPolicy) -> Void) {
        if klarnaSDK.shouldFollowNavigation(withRequest: navigationAction.request) != true {
            decisionHandler(.cancel)
        } else {
	    decisionHandler(.allow)
    	}
   }
```
 **Note regarding the last bit of code below:** Not the same as in the integration guide (https://developers.klarna.com/documentation/in-app/ios/steps-hybrid/#more-about-the-klarna-hybrid-sdk-listener) since xCode did not think that code "conformed to protocol ‘KlarnaHybridEventListener’". Instead I was forced to use the stubs below suggested by xCode. Could this be a possible cause for the issue?! 
```
    func klarnaWillShowFullscreen(inWebView webView: KlarnaWebView, completionHandler: @escaping () -> Void) {
        print("klarnaWillShowFullscreen")
    }
    
    func klarnaDidShowFullscreen(inWebView webView: KlarnaWebView, completionHandler: @escaping () -> Void) {
        print("klarnaDidShowFullscreen")
    }
    
    func klarnaWillHideFullscreen(inWebView webView: KlarnaWebView, completionHandler: @escaping () -> Void) {
        print("klarnaWillHideFullscreen")
    }
    
    func klarnaDidHideFullscreen(inWebView webView: KlarnaWebView, completionHandler: @escaping () -> Void) {
        print("klarnaDidHideFullscreen")
    }
    
    func klarnaFailed(inWebView webView: KlarnaWebView, withError error: KlarnaMobileSDKError) {
        print("klarnaFailed")
    }
}
```

**Expected behavior**
The KlarnaHybridEventListener functions should be triggered when the Klarna popup form takes over in fullscreen mode and when the fullscreen mode is exited. 

**Device and version:**
 - Device: iPhone 7
 - OS version: iOS 13.3
 - XCode version: 11.3.1
 - Klarna In-App SDK version: 2.0.9

I can't release my app to App Store with issue https://github.com/klarna/klarna-mobile-sdk/issues/12 so reverting to 2.0.8 is not an option. Please advice.

**Comment by AmyNgithub** [comment]
Any advice on this?

**Comment by polar133** [comment]
Hi @AmyNgithub we will check this issue. Will reply back when we have more info.

**Comment by AmyNgithub** [comment]
I checked this issue with version 2.0.10 (ref: https://github.com/klarna/klarna-mobile-sdk/issues/10) just to be sure that the issues weren't related (even though it seemed unlikely). And the this problem is still present in version 2.0.10.

**Comment by polar133** [comment]
@AmyNgithub please, contact me thought this email carlos.jimenez@klarna.com so we can find a way to debug this issue, because for our side it seems that KlarnaHybridEventListener is been called.

**Comment by AmyNgithub** [comment]
Turned out that the issue was caused by two things:

1. In the stubs suggested by xCode I had to add completionHandler(). 
```
    func klarnaWillShowFullscreen(inWebView webView: KlarnaWebView, completionHandler: 
@escaping () -> Void) {
        print("klarnaWillShowFullscreen")
        completionHandler()
    }
    
    func klarnaDidShowFullscreen(inWebView webView: KlarnaWebView, completionHandler: @escaping () -> Void) {
        print("klarnaDidShowFullscreen")
        completionHandler()
    }
    
    func klarnaWillHideFullscreen(inWebView webView: KlarnaWebView, completionHandler: @escaping () -> Void) {
        print("klarnaWillHideFullscreen")
        completionHandler()
    }
    
    func klarnaDidHideFullscreen(inWebView webView: KlarnaWebView, completionHandler: @escaping () -> Void) {
        print("klarnaDidHideFullscreen")
        completionHandler()
    }
    
    func klarnaFailed(inWebView webView: KlarnaWebView, withError error: KlarnaMobileSDKError) {
        print("klarnaFailed")
    }

```
2. I Opened a new page in a new WebView which I had forgotten to add to the SDK
`klarnaSDK.addWebView(self.mySecondWebView)`

Thank you for the assistance!
