### ISSUE TITLE
KlarnaOSMView - Crash in iPad on clicking share button

### ISSUE THREAD

**Issue by Gopesh** [klarna/klarna-mobile-sdk#199]
**Describe the bug**
KlarnaOSMView have learn more as hyperlink and clicking on hyperlink, opens web controller ProgressNavigationController and then if you click share button in iPad, it crashes

**To Reproduce**
1. Go to ProgressNavigationController from KlarnaOSMView
2. Click on ShareButton in bottom toolbar
3. App will crash with this exception "UIPopoverPresentationController should have a non-nil sourceview or barButtonItem set before the presentation occurs.

**Expected behavior**
App should not crash

**Screenshots**

**Device and version:**
 - iPad
 - OS version: Any OS version 
 - Klarna In-App SDK version - Currently using 2.6.4

**Merchant Name**
Please state the merchant's name and the application's name that is facing the issue using the SDK.

**Impact Level**
What is the impact level of this bug on the merchant and its customers? Is it happening in production? Is it a blocking issue for development?  etc. 

**Additional context**

**Comment by polar133** [comment]
Hi @Gopesh , thanks for sharing this issue. We will investigate, and be back once we have more information to share. If you have any further questions or concerns, please don't hesitate to reach out.

**Comment by Gopesh** [comment]
Hi @polar133 ,
Thanks for quick response on issue. Is it fixed? If yes, in which it will be available?

**Comment by polar133** [comment]
@Gopesh We found the problem. UIActivityViewController was missing the sourceview for iPad. We are really sorry that we forgot to add this validation and its going to be fixed on the next release (2.6.6). Once it's released i will notify here. Again, thanks for sharing this finding and we are sorry for any inconvenience.

**Comment by Gopesh** [comment]
@polar133 do we have any release date for 2.6.6?

**Comment by polar133** [comment]
Hi @Gopesh, sorry for the late reply. Version 2.6.6 is now available. Please, give a try and let us know how it goes.

**Comment by polar133** [comment]
Hi. I will close this ticket since there is no update. If you still have the issue please don't hesitate to open it again and provide more information.
