### ISSUE TITLE
Problem with positioning WebView content

### ISSUE THREAD

**Issue by ulbiboozt** [klarna/klarna-mobile-sdk#203]
Faced with the problem of positioning web content for viewing. If we have a webView that is not fully displayed on the screen, partially hidden outside the screen from above, and we click on it, the content moves below and an additional empty space is formed. Which is why not all content is displayed.

How it looks after the steps I described above. The red square highlights the zone that is being added to the webView:
<img width="300" alt="Screenshot 2023-07-13 at 10 27 35" src="https://github.com/klarna/klarna-mobile-sdk/assets/139443030/dcdb5fa3-9f68-4aca-b85b-5450821d81a1">

 - Device:  iPhone 14 Pro
 - OS version: iOS 16.4
 - Klarna In-App SDK version 2.6.6

It has a very strong effect due to the fact that it affects in-app purchases

**Comment by NMGuner** [comment]
Issue has been addressed by the team owning the payment widget in web.
