### ISSUE TITLE
Xcode 15.0 compilation error 

### ISSUE THREAD

**Issue by AnastasiaKovalevaInterexy** [klarna/klarna-mobile-sdk#220]
**Describe the bug:**

After moving my project to Xcode 15, i was needed to update Firebase library, before it was 8.8.0 version (it's quite an old project), after updating it to latest version (10.18.0) the issue with Firebase was resolved but started appearing error for import KlarnaMobileSDK. I have also updated KlarnaMobileSDK to latest version 2.6.12. We are using spm to work with library. 
If i remove import of KlarnaMobileSDk i'm able to run the project and all works. 

The erros i got (they are changing time to time):
> Failed to build module ‘KlarnaMobileSDK’; this SDK is not supported by the compiler (the SDK is built with ‘Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)’, while this compiler is ‘Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)’). Please select a toolchain which matches the SDK.

> Compiling for iOS 10.0, but module ‘Network’ has a minimum deployment target of iOS 14.0: /Users/anastasia/Library/Developer/Xcode/DerivedData/HerCare-ededixhaufkjpyhhoieysxzfijri/Build/Products/Debug-iphonesimulator/Network.swiftmodule/arm64-apple-ios-simulator.swiftmodule

> Failed to build module 'KlarnaMobileSDK' for importation due to the errors above; the textual interface may be broken by project issues or a compiler bug

<img width="1509" alt="Screenshot 2023-12-01 at 10 24 44" src="https://github.com/klarna/klarna-mobile-sdk/assets/132066185/9e485745-3a1e-4845-8f48-071f89ffbc58">

I have tried:
- cleaning the project and derived data, reinstalling libraries. 
- checked all iOS deployments targets and we have all set to minimum ios version 14.0
- tried on different Xcodes (15.0, 15.0.1, 15.1 Beta 3) in all have the same issue, but in Xcode 14 all is working properly and i can run the app. 
- tried to work through cocoapods and received same error.

**Comment by AnastasiaKovalevaInterexy** [comment]
@polar133 could you have a look into it? we are not able to run our app on Xcode15....

**Comment by jorgepalac1o** [comment]
Hi @AnastasiaKovalevaInterexy have you try to use it with Xcode 15.1? When added to an empty project as a dependency in xcode 15.0 the library doesn't show those errors. 
Besides cleaning the cache, verify that the xcode command line tools version used is the one that has Xcode 15, you can check it with the `xcode-select --print-path` command and should show you which xcode cmd line tools is using.
And last, but not least, a new version of the sdk was release yesterday, please update to that version as well.
