### ISSUE TITLE
PrivacyInfo.xcprivacy file contains invalid tracking information

### ISSUE THREAD

**Issue by mammaiap** [klarna/klarna-mobile-sdk#235]
**ITMS-91064: Invalid tracking information** - A PrivacyInfo.xcprivacy file contains invalid tracking information at the following path: “Frameworks/KlarnaMobileSDK.framework/PrivacyInfo.xcprivacy”. NSPrivacyTracking must be true if NSPrivacyTrackingDomains isn’t empty. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, keys and values in your app’s privacy manifest must be valid. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

i am getting the above warning from AppStoreConnect, after using the latest KlarnaMobileSDK.framework version: 2.6.17 (which supports the Privacy manifest).. can you please fix the PrivacyInfo.xcprivacy file which contains the invalid tracking information?

Thanks & Regards,
Muthlingam

**Comment by jorgepalac1o** [comment]
Hi @mammaiap @piercifani thank you for letting us know about this issue, our team will work on the fix for it!

**Comment by Nehcgnos** [comment]
+1

**Comment by joseewu** [comment]
hi 👋 same issue here.

**Comment by emanuelaferrara** [comment]
Hi, I've updated to the last ios version (2.6.18), but now I have a crash launching the app on physical device, with the following error:

dyld[1092]: Library not loaded: @rpath/KlarnaMobileSDK.framework/KlarnaMobileSDK

This is not happening with the version 2.6.17.
Let me know if you need further information.

Thank you
