### ISSUE TITLE
KlarnaMobileSDK not compatible with Swift 5.3 and Xcode 12

### ISSUE THREAD

**Issue by AmyNgithub** [klarna/klarna-mobile-sdk#53]
**Describe the bug**
SDK can't be imported in xCode 12 with swift 5.3.

**To Reproduce**
1. Install xCode 12 (GM seed - [https://developer.apple.com/xcode/]())
2. Update to latest version of KlarnaMobileSDK (2.0.21)
2. Open project and open file with the line "import KlarnaMobileSDK"
3. Warning stating that: "Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler: <project-path>/Pods/KlarnaMobileSDK/ios/xcode-11.7-fat/KlarnaMobileSDK.framework/Modules/KlarnaMobileSDK.swiftmodule/arm64-apple-ios.swiftmodule" appears.

**Expected behavior**
For KlarnaMobileSDK to be able to be imported with Swift 5.3 compiler.

**Screenshots**
N/A

**Device and version:**
 - Device: N/A
 - OS version: N/A
 - Klarna In-App SDK version 2.0.21
 - xCode version 12.0 (12A7209)
 - Swift version 5.3

**Additional context**
I need to be able to compile my app with KlarnaMobileSDK in xCode 12 and Swift 5.3 to adapt my app to the new changes in iOS 14.
I realise that xCode 12 was released as a GM seed yesterday so I fully understand why it doesn't work yet, but I thought I might as well "get the ball rolling" :)

**Comment by polar133** [comment]
Hi @AmyNgithub, we are working for making it available ASAP. 

We are testing in the branch https://github.com/klarna/klarna-mobile-sdk/tree/ios_release_2.0.22. In case that you want to test it you can specify in your Podfile :

`pod "KlarnaMobileSDK", :git => "https://github.com/klarna/klarna-mobile-sdk", :branch => "ios_release_2.0.22",`

reminder: It's still a WIP so it might be further commits until we release a final version.

**Comment by AmyNgithub** [comment]
@polar133 Thanks! I will try that while I wait for the final version :)

**Comment by AmyNgithub** [comment]
Hi again, 
Noticed while I was trying to upload my app to TestFlight to allow other members of my team to test the iOS14 fixes I made that Apple suddenly demands that I specify NSCameraUsageDescription key. 

When I searched my project for "camera" the following line appeared a couple of times in KlarnaMobileSDK-Swift.h: "- (void)onCameraPermissionDeniedWithShowedPrompt:(BOOL)showedPrompt;".

Have you added usage of the camera? Is this something new or will it be removed in the final version? If not, what is the camera used for?

**Comment by polar133** [comment]
Hi, that's for card scanning, a feature that we release before and should be only available in the "full" version. In this case, if you are using the pod that i shared before (with subspec to xcode-12.0-gm-fat-basic) should not require camera, but we will look further into it. thanks for the feedback. 

In case that you want to keep testing, please, add the camera permission (even if not needed for now) so you can upload to testflight for now. But please, don't use this version for a release.

**Comment by AmyNgithub** [comment]
Ok! Thanks for the quick answer. I will wait for the full version before releasing beyond internal testning.

**Comment by bobergj** [comment]
Please distribute the SDK as an .xcframework, then it should work across Xcode versions, and Swift compiler versions.
Distributing binary Swift modules as a .framework (rather than an .xcframework) is not supported by Apple - there are a bunch of discussions on https://forums.developer.apple.com about this.

Binary Frameworks in Swift
https://developer.apple.com/videos/play/wwdc2019/416
> "So, in this talk, I'm going to introduce you to XCFrameworks, the new supported way to distribute binary frameworks."
> "And when you enable Build Libraries for Distribution, you're telling the compiler to generate one of these stable interfaces whenever it builds your framework."

**Comment by polar133** [comment]
Hi @AmyNgithub we release 2.0.22, it should not require the camera permission.

**Comment by AmyNgithub** [comment]
Hi @polar133 ,
I downloaded version 2.0.22 and tried to upload to TestFlight but it still complains about camera permission.

**Comment by polar133** [comment]
Hi @AmyNgithub we are releasing a new version 2.0.23. Please check that version and let us know if that one works. 

(not available yet because CDN from Cocoapods is down, will update when it's published)

**Comment by AmyNgithub** [comment]
@polar133 I apologise. It turns out that I accidentally reverted to your test branch when I tried to solve another issue which occurred when I installed version 2.0.22. But perhaps version 2.0.23 will somehow solve the issue below...
<img width="742" alt="klarnamobilesdkissue" src="https://user-images.githubusercontent.com/11645053/93973965-67a3a400-fd75-11ea-9d53-70130f2e1ce3.png">

**Comment by polar133** [comment]
@AmyNgithub 2.0.23 it's released. Please give a try and let us know if there are issues with it please.

**Comment by AmyNgithub** [comment]
@polar133 Tried 2.0.23 and I no longer have the issue with the camera permission or the other issues from my previous comment!

**Comment by polar133** [comment]
Thanks for the update @AmyNgithub.
