### ISSUE TITLE
Swift package download takes a long time due to repo size

### ISSUE THREAD

**Issue by bobergj** [klarna/klarna-mobile-sdk#71]
**Describe the bug**
The swift package with the xcframework is ~700mb.

**To Reproduce**
1. Configure https://github.com/klarna/klarna-mobile-sdk as a swift package dependency in an Xcode project
2. Wait a long time

**Expected behavior**
The swift framework is in it's own repo, so the download is just 30mb.

**Screenshots**
n/a

**Device and version:**
 - Xcode 12.1

**Additional context**
n/a

**Comment by polar133** [comment]
Hi @bobergj, thanks for the comment. Following the suggestion, the package file for the SPM will be available in [https://github.com/klarna/klarna-mobile-sdk-spm](https://github.com/klarna/klarna-mobile-sdk-spm) so it will download only the .xcframework needed for the integration. Please, give a try and let is know how did it go.

**Comment by danpalmer** [comment]
Thanks for this! Just came looking for solutions to the ~6GB repository and found this. The new SPM repo is working well for us.

**Comment by bobergj** [comment]
@polar133:
> Please, give a try and let is know how did it go.

It's good, so for my part you can close this.

**Comment by polar133** [comment]
Thanks for the update.
