### ISSUE TITLE
Unable to install app on physical device using SPM

### ISSUE THREAD

**Issue by josecriane** [klarna/klarna-mobile-sdk#72]
**Describe the bug**
When we try add KlarnaMobileSDK using SPM the app is unable to install on physical device

**To Reproduce**
We add klarna-mobile-sdk to a core library and the app is unable to install. The structure of project is:

App > Core Library > KlarnaMobileSDK (with SPM)

Compile and run, xcode show a alert message "Unable to Install app".

**Screenshots**
<img width="863" alt="Screenshot 2020-11-13 at 11 24 55" src="https://user-images.githubusercontent.com/1725790/99062182-dd243780-25a2-11eb-89ad-705a04151184.png">

**Device and version:**
 - Device: iPod 7th gen
 - OS version: iOS 13.5.1
 - Klarna: lastest SPM version

**Additional context**
Adding the sdk manually it works.
In the simulator SPM works.
I see that Firebase was a similar problem. https://github.com/firebase/firebase-ios-sdk/issues/6360

**Comment by josecriane** [comment]
I created a example workspace with the problem
https://github.com/josecriane/klarna-spm-error-example

**Comment by polar133** [comment]
Thanks for the example @josecriane we will take a look at it.

**Comment by polar133** [comment]
Hi @josecriane, I checked out the example and found out that it's a [xcode bug](https://forums.swift.org/t/swiftpm-binarytarget-dependency-and-code-signing/38953 ) that is going on since Xcode 12. But i managed to make it work following the [pspdfkit guide](https://pspdfkit.com/guides/ios/current/knowledge-base/library-not-found-swiftpm/).

**Comment by simonpierreroy** [comment]
This is fixed in Xcode 12.2 and is released to bad signing when building to device from Xcode.

**Comment by omarbh** [comment]
Hi, this ticket will be closed, feel free to reopen you are still having the issue.
