### ISSUE TITLE
LICENSE file is missing but still specified in podspec

### ISSUE THREAD

**Issue by richellis** [klarna/klarna-mobile-sdk#78]
**Describe the bug**
My company uses the `cocoapods-acknowledgements` plugin. After pod update to 2.0.30, I see this warning:
```
[!] Unable to read the license file `LICENSE` for the spec `KlarnaMobileSDK (2.0.30)`
```

The podspec still specifies a LICENSE file, but the file appears to have been deleted sometime after 2.0.28. 

**To Reproduce**
1. `pod update KlarnaMobileSDK`

**Expected behavior**
LICENSE file should be available. Or `license` section in podspec should be removed or fixed.

**Comment by polar133** [comment]
Hi @richellis. Thanks for reaching out with this warning, we already uploaded the LICENSE file again, sorry for any inconvenience. Please, try again and let us know how did it go.

**Comment by polar133** [comment]
Hi @richellis. Thanks for reaching out with this warning, we already uploaded the LICENSE file again, sorry for any inconvenience. Please, try again and let us know how did it go.

Steps to update the pod:
- pod deintegrate
- pod cache clean --all
- pod install --repo-update

**Comment by richellis** [comment]
Worked!
