### ISSUE TITLE
Support arm64 simulator in .xcframework and SPM package

### ISSUE THREAD

**Issue by bobergj** [klarna/klarna-mobile-sdk#80]
**Is your feature request related to a problem? Please describe.**

The .xcframework does not support the arm64 iOS Simulator (the simulator on M1 Macs).

As we eventually get M1 Macs for our developers, without fixing this, they won't be able to build and run our app on the simulator.

**Describe the solution you'd like**

Build the .xcframwork with an arm64 iOS simulator slice.
A correct .xcframework, supporting the arm64 simulator, would contain Info.plist entries as follows:
```
<dict>
	<key>DebugSymbolsPath</key>
	<string>dSYMs</string>
	<key>LibraryIdentifier</key>
	<string>ios-arm64_i386_x86_64-simulator</string> <==========
	<key>LibraryPath</key>
	<string>KlarnaMobileSDK.framework</string>
	<key>SupportedArchitectures</key>
	<array>
	        <string>arm64</string>      <============
		<string>i386</string>
		<string>x86_64</string>
	</array>
	<key>SupportedPlatform</key>
	<string>ios</string>
	<key>SupportedPlatformVariant</key>
	<string>simulator</string>
</dict>
```
Compare to: https://github.com/klarna/klarna-mobile-sdk/blob/master/ios/XCFramework/full/universal/KlarnaMobileSDK.xcframework/Info.plist

**Comment by bobergj** [comment]
How's the investigation going? We have several developers with M1 Macs that have to run Xcode under Rosetta due to this.

**Comment by polar133** [comment]
Hi, sorry for the delay. Next release will be available.

**Comment by polar133** [comment]
Hi @KirbyInGitHub, @bobergj. Sorry for the delay on this update. Our latest release (2.0.37) should support arm64 in xcframework (https://github.com/klarna/klarna-mobile-sdk-spm). Please, give a try and let us know how did it went with this version. I will close the ticket but if there is any issue, feel free to open it again.
